# Generated by Django 5.2.14 on 2026-05-08 14:50

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('account_type', models.CharField(choices=[('brokerage', 'Биржа'), ('token', 'Токены / Finstore'), ('deposit', 'Депозит'), ('cash', 'Наличные'), ('crypto', 'Крипта'), ('cfd', 'CFD'), ('bank', 'Банк'), ('other', 'Другое')], max_length=24)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('blocked_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('asset_class', models.CharField(choices=[('exchange', 'Биржа'), ('token', 'Токены / Finstore'), ('deposit', 'Депозит'), ('cash', 'Наличные'), ('crypto', 'Крипта'), ('cfd', 'CFD'), ('other', 'Другое')], max_length=24)),
                ('price_currency', models.CharField(blank=True, max_length=3)),
                ('current_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='FXRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
            ],
            options={
                'ordering': ['from_currency', 'to_currency'],
                'constraints': [models.UniqueConstraint(fields=('from_currency', 'to_currency'), name='unique_fx_pair')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('interest', 'Interest'), ('fee', 'Fee'), ('transfer', 'Transfer')], max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('asset_quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='completed', max_length=24)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='portfolio.asset')),
                ('destination_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='portfolio.account')),
                ('source_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='portfolio.account')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
    ]
