# Generated by Django 5.2.14 on 2026-05-08 15:01

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['name'], 'verbose_name': 'счет', 'verbose_name_plural': 'счета'},
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['symbol'], 'verbose_name': 'актив', 'verbose_name_plural': 'активы'},
        ),
        migrations.AlterModelOptions(
            name='fxrate',
            options={'ordering': ['from_currency', 'to_currency'], 'verbose_name': 'валютный курс', 'verbose_name_plural': 'валютные курсы'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-occurred_at', '-id'], 'verbose_name': 'операция', 'verbose_name_plural': 'операции'},
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('brokerage', 'Биржа'), ('token', 'Токены / Finstore'), ('deposit', 'Депозит'), ('cash', 'Наличные'), ('crypto', 'Крипта'), ('cfd', 'CFD'), ('bank', 'Банк'), ('other', 'Другое')], max_length=24, verbose_name='Тип счета'),
        ),
        migrations.AlterField(
            model_name='account',
            name='blocked_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Заблокированная сумма'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='account',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Начальный остаток'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_class',
            field=models.CharField(choices=[('exchange', 'Биржа'), ('token', 'Токены / Finstore'), ('deposit', 'Депозит'), ('cash', 'Наличные'), ('crypto', 'Крипта'), ('cfd', 'CFD'), ('other', 'Другое')], max_length=24, verbose_name='Класс актива'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Текущая цена'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='price_currency',
            field=models.CharField(blank=True, max_length=3, verbose_name='Валюта цены'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(max_length=32, unique=True, verbose_name='Тикер / код'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='fxrate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='fxrate',
            name='from_currency',
            field=models.CharField(max_length=3, verbose_name='Из валюты'),
        ),
        migrations.AlterField(
            model_name='fxrate',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='fxrate',
            name='to_currency',
            field=models.CharField(max_length=3, verbose_name='В валюту'),
        ),
        migrations.AlterField(
            model_name='fxrate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='portfolio.asset', verbose_name='Актив'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='asset_quantity',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18, verbose_name='Количество актива'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='portfolio.account', verbose_name='Счет зачисления'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Комиссия'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='occurred_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='portfolio.account', verbose_name='Счет списания'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('completed', 'Исполнено'), ('failed', 'Ошибка'), ('canceled', 'Отменено')], default='completed', max_length=24, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа'), ('deposit', 'Пополнение'), ('withdraw', 'Вывод'), ('interest', 'Доход'), ('fee', 'Комиссия'), ('transfer', 'Перевод')], max_length=24, verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
