# Generated by Django 5.2.14 on 2026-05-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_account_options_alter_asset_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fxrate',
            name='effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата курса'),
        ),
    ]
