# Generated by Django 5.2.14 on 2026-05-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_account_currency_alter_asset_price_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='blocked_amount',
        ),
    ]
