# Generated by Django 5.2.14 on 2026-05-08 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_account_blocked_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='portfolio.account', verbose_name='Счет'),
        ),
    ]
