# Generated by Django 5.2.14 on 2026-05-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_asset_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='deposit_annual_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Годовая процентная ставка'),
        ),
        migrations.AddField(
            model_name='asset',
            name='deposit_initial_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Начальный взнос'),
        ),
        migrations.AddField(
            model_name='asset',
            name='deposit_interest_payout_frequency',
            field=models.CharField(blank=True, choices=[('monthly', '1 раз в месяц'), ('semi_monthly', '2 раза в месяц')], max_length=24, verbose_name='Периодичность выплаты процентов'),
        ),
        migrations.AddField(
            model_name='asset',
            name='deposit_interest_payout_method',
            field=models.CharField(blank=True, choices=[('to_account', 'На счет'), ('capitalization', 'Капитализация')], max_length=24, verbose_name='Способ выплаты процентов'),
        ),
        migrations.AddField(
            model_name='asset',
            name='deposit_open_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата открытия'),
        ),
        migrations.AddField(
            model_name='asset',
            name='deposit_revocability',
            field=models.CharField(blank=True, choices=[('revocable', 'Отзывный'), ('irrevocable', 'Безотзывный')], max_length=24, verbose_name='Тип депозита'),
        ),
        migrations.AddField(
            model_name='asset',
            name='deposit_term_end',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия'),
        ),
        migrations.AddField(
            model_name='asset',
            name='deposit_term_type',
            field=models.CharField(blank=True, choices=[('term', 'Срочный'), ('open_ended', 'Бессрочный')], max_length=24, verbose_name='По сроку'),
        ),
        migrations.AddField(
            model_name='asset',
            name='deposit_weekend_rollover',
            field=models.BooleanField(default=False, verbose_name='Перенос выплаты с выходного дня'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_class',
            field=models.CharField(choices=[('exchange', 'Биржа'), ('token', 'Токены / Finstore'), ('deposit', 'Депозит'), ('cash', 'Наличные'), ('crypto', 'Крипта'), ('cfd', 'CFD'), ('other', 'Другое')], max_length=24, verbose_name='Тип актива'),
        ),
    ]
