# Generated by Django 5.2.14 on 2026-05-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_asset_deposit_annual_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='closed_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
    ]
