# Generated by Django 5.2.14 on 2026-05-08 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_asset_closed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('topup_date', models.DateField(verbose_name='Дата пополнения')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Сумма пополнения')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topups', to='portfolio.asset', verbose_name='Депозит')),
            ],
            options={
                'verbose_name': 'пополнение депозита',
                'verbose_name_plural': 'пополнения депозитов',
                'ordering': ['topup_date', 'id'],
            },
        ),
    ]
