# Generated by Django 5.2.14 on 2026-05-08 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_deposittopup'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposittopup',
            name='source_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit_topups', to='portfolio.account', verbose_name='Счет списания'),
        ),
    ]
