# Generated by Django 5.2.14 on 2026-05-09 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_deposittopup_source_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposittopup',
            name='cash_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_topup_record', to='portfolio.transaction', verbose_name='Денежная операция'),
        ),
    ]
