# Generated by Django 5.2.14 on 2026-05-09 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_deposittopup_cash_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositCapitalizationAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('capitalization_date', models.DateField(verbose_name='Дата капитализации')),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Сумма процентов')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capitalization_adjustments', to='portfolio.asset', verbose_name='Депозит')),
            ],
            options={
                'verbose_name': 'корректировка капитализации',
                'verbose_name_plural': 'корректировки капитализации',
                'ordering': ['capitalization_date', 'id'],
                'constraints': [models.UniqueConstraint(fields=('asset', 'capitalization_date'), name='unique_capitalization_adjustment')],
            },
        ),
    ]
