# Generated by Django 5.2.14 on 2026-05-09 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_depositcapitalizationadjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositRateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('effective_date', models.DateField(verbose_name='Дата начала действия')),
                ('annual_rate', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Годовая ставка')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_changes', to='portfolio.asset', verbose_name='Депозит')),
            ],
            options={
                'verbose_name': 'изменение ставки депозита',
                'verbose_name_plural': 'изменения ставки депозита',
                'ordering': ['effective_date', 'id'],
                'constraints': [models.UniqueConstraint(fields=('asset', 'effective_date'), name='unique_deposit_rate_change')],
            },
        ),
    ]
